spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=rideease;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=rideease_user
spring.datasource.password=rideease_user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

jwt.secret=RideEaseSuperSecretKeyForJwtAuthentication2026
jwt.expiration=86400000

spring.sql.init.mode=never